#!/bin/sh

# pull latest from git repo
git pull

# Create directories
[ ! -d "${HOME}/.local/bin" ] && mkdir ${HOME}/.local/bin

#
# Check for needed software
#
missing=""

# python3
if ! command -v python3 >/dev/null; then
    missing="${missing} python3"
fi

# nodejs v14.x / npm
if [[ $(node -v) != v14.* ]]; then
    missing="${missing} node(v14.x)"
fi
if ! command -v npm >/dev/null; then
       missing="${missing} npm"
fi

# kill update if any programs are missing
if [ -n "${missing}" ]; then
	echo "Missing software:${missing}"
	killall rcup
fi
