# maintained by dotfiles - changes will be overwritten
# .bashrc

# Return in not interactive
[[ $- != *i* ]] && return

# Source global definitions
[[ -f /etc/bashrc ]] && . /etc/bashrc
[[ -f /etc/bash.bashrc ]] && . /etc/bash.bashrc

# Source prompt info
source ${HOME}/.bash/prompt

# local python config
export PYTHONUSERBASE=${HOME}/.python
export PATH=${HOME}/.python/bin:$PATH
source ${HOME}/.python/bin/virtualenv-sh.bash

# Change tmux status bar if tmux is running locally
if [ -n "${TMUX}" -a -z "${SSH_CONNECTION}" ]; then
    tmux set-option status-bg '#80ff80' >/dev/null
fi


# User specific aliases and functions


# Source bashrc.local if availible
[[ -f ${HOME}/.bashrc.local ]] && . ${HOME}/.bashrc.local

# Source APPS directory config
[[ -f ${HOME}/Apps/apps-config ]] && . ${HOME}/Apps/apps-config
