# maintained by dotfiles - changes will be overwritten
# .bashrc

source ${HOME}/.config/bash/functions

# remove ~/bin from path and  make sure ~/.local/bin is at the front 
alter_path remove ${HOME}/bin

alter_path remove ${HOME}/.local/bin
alter_path add ${HOME}/.local/bin


# Return in not interactive
[[ $- != *i* ]] && return

# Source global definitions
[[ -f /etc/bashrc ]] && . /etc/bashrc
[[ -f /etc/bash.bashrc ]] && . /etc/bash.bashrc

# return if unsupported
[ "${DISTRO}" = "unsupported" ] && return


# Source prompt info
source ${HOME}/.config/bash/prompt

# Change tmux status bar if tmux is running locally
if [ -n "${TMUX}" -a -z "${SSH_CONNECTION}" ]; then
    tmux set-option status-bg '#80ff80' >/dev/null
fi

# Enable some software collections on SL6 (if installed)
if [ "${DISTRO}" = "sl6" ]; then
    if scl -l | grep -q python33; then
        enable_scl python33
    fi
fi

# Add virtualenv-sh support
[ -n "${HAS_QUOTA}" ] && WORKON_HOME="/tmp/pas37-venv"
[ "$(hostname -s)" = "lnx7233" ] && WORKON_HOME="/scratch/pas37/virtualenvs"

source ${HOME}/.config/bash/virtualenv-sh.bash


# Source bashrc.local if availible
[[ -f ${HOME}/.bashrc.local ]] && . ${HOME}/.bashrc.local
