# maintained by dotfiles - changes will be overwritten
# .bash_profile

source ${HOME}/.config/bash/functions

# remove ~/bin from path and  make sure ~/.local/bin is at the front 
alter_path remove ${HOME}/bin

alter_path remove ${HOME}/.local/bin
alter_path add ${HOME}/.local/bin

unset -f alter_path


# Return if not interactive
[[ $- != *i* ]] && return


if [ "${DISTRO}" != "unsupported" ]; then
    # Load keychain (inherit if existing SSH_AUTH_SOCK)
    if [ "$SSH_AUTH_SOCK" ]; then
        inherit="--inherit any"
    fi
    eval `keychain --eval --dir ${HOME}/.cache --agents ssh ${inherit}`

    # If SSH connection with TTY use tmux (check for loops / no tmux)
    if [ -n "$SSH_TTY" -a "${TERM:0:6}" != "screen" -a -n "$(command -v tmux)" ]
    then
        hostent=$(/usr/bin/getent hosts ${SSH_CONNECTION%% *})
        if [ -n "${hostent}" ];then
	    host=$(echo ${hostent##* } | cut -d'.' -f1)
        else
	    host="unknown"
        fi
        if tmux -V >/dev/null 2>/dev/null; then
	    tmux has -t ${host} && tmux attach -t ${host} || tmux new -s ${host}
	    exit
        fi
    fi
fi

# Get the aliases and functions
[[ -f ~/.bashrc ]] &&  . ~/.bashrc
